### ISSUE TITLE
How to change embedding vector size ? 

### ISSUE THREAD

**Issue by kaushil24** [faustomorales/keras-facenet#2]
The following code snipped generates an embedding with shape ` (1,512)`.  How can I change it to 1*128 ? 
`
img = cv2.imread('sample.jpg')`
`embedded = embedder.embeddings([img])`
`embedded.shape
`
Outout: `(1,512)`

**Comment by faustomorales** [comment]
The embedding size is dependent on which model you use. I assume that you used `embedder = FaceNet()`, which means the default model key (`20180402-114759`) was used. This model has embedding size 512.

If you want an embedding size of 128, you should use `embedder = FaceNet(key='20170511-185253')` or `embedder = FaceNet(key='20170512-110547')`. See the `dimensions` parameter for each model in `keras-facenet/metadata.py` for more information.

Please note that the distance metric also varies depending on the model. You can get the model distance metric from `embedder.metadata['distance_metric']`.

Hope this helps!

**Comment by faustomorales** [comment]
Closing this issue for now. If you have trouble, please feel free to comment back and we can re-open.
