### ISSUE TITLE
Compute the distance between two embeddings

### ISSUE THREAD

**Issue by josephernest** [faustomorales/keras-facenet#3]
Congrats for this nice project!

How do you compute the distance between two 128D embeddings? 

Do you pre-normalize it? and then calculate a Euclidean distance?

What kind of threshold do you use to decide it's the same person?

**Comment by RafaelLeonhardt** [comment]
About how to get the best threshold you can check this article => https://medium.com/@mustafaazzurri/face-recognition-system-and-calculating-frr-far-and-eer-for-biometric-system-evaluation-code-2ac2bd4fd2e5

**Comment by faustomorales** [comment]
The threshold is dependent on your tolerance for false positives and false negatives. You can use the built-in `compute_distance` method to compute the distance.

```python
from keras_facenet import FaceNet
embedder = FaceNet()

# Gets a detection dict for each face
# in an image. Each one has the bounding box and
# face landmarks (from mtcnn.MTCNN) along with
# the embedding from FaceNet.
detections = embedder.extract(image, threshold=0.95)

# If you have pre-cropped images, you can skip the
# detection step.
embeddings = embedder.embeddings(images)

distance = embedder.compute_distance(embeddings[0], embeddings[1])
```
