### ISSUE TITLE
About Pre-trained Model

### ISSUE THREAD

**Issue by Adeel-Intizar** [faustomorales/keras-facenet#4]
Hello, Thank you for your great work

Can you give me the link of pre-trained model, that is being used in this implementation?
And what distance does it compute, is it cosine distance or some other?
And what is good threshold value for it?
Thank you

**Comment by faustomorales** [comment]
Hi there! The distance metrics and model URLs are available [here](https://github.com/faustomorales/keras-facenet/blob/master/keras_facenet/metadata.py). The appropriate distance threshold is use-case and model specific. I recommend evaluating the precision and recall scores on a relevant dataset to decide what is appropriate.

**Comment by Adeel-Intizar** [comment]
What if I want to use the keras weights .h5 file instead of downloading it again and again when the script is started
