### ISSUE TITLE
L2 or cosine distance?

### ISSUE THREAD

**Issue by bmachin** [faustomorales/keras-facenet#6]
Hey, thanks for wrapping David's implementation! I've used it quite a lot and it's great to be able to use it even more easily with your project.

I've been using the L2 distance to compare embeddings from Facenet, but I hear that cosine distance may be more suitable sometimes. I guess it depends on the actual model and how it was trained. Could you clarify on this point for this implementation? 

Best,
Benjamin.-

**Comment by faustomorales** [comment]
Hi there -- Thank you for the kind words! The library contains metadata for each model indicating which distance metric should be used based on how the model was trained, inferred from the content of the wiki in the [original repository](https://github.com/davidsandberg/facenet/wiki/Training-using-the-VGGFace2-dataset). Please see https://github.com/faustomorales/keras-facenet/issues/4#issuecomment-774574197 for more information.
